ux_icons:
    # The local directory where icons are stored
    icon_dir: '%kernel.project_dir%/assets/icons'

    # Default attributes to add to all icons
    default_icon_attributes:
        fill: currentColor
        'font-size': '1.25em'
        height: '0.9em'
        width: '0.9em'

    # Icon aliases (alias => icon name)
    aliases:
#        dots: 'clarity:ellipsis-horizontal-line'
#        'tabler:save': 'tabler:device-floppy'

    # Configuration for the "on demand" icons powered by Iconify.design
#    iconify:
#        enabled: true
#
#        # Whether to use the "on demand" icons powered by Iconify.design
#        on_demand: true
#
#        # The endpoint for the Iconify API
#        endpoint: 'https://api.iconify.design'

    # Whether to ignore errors when an icon is not found
#    ignore_not_found: false