proxy:
    domains:
        - minutenbild

http:
    #document_root: public/ # Path to the project document root
    #passthru: index.php # Project passthru index
    #port: 8000 # Force the port that will be used to run the server
    #preferred_port: 8001 # Preferred HTTP port [default: 8000]
    #p12: path/to/p12_cert # Name of the file containing the TLS certificate to use in p12 format
    #allow_http: true # Prevent auto-redirection from HTTP to HTTPS
    #no_tls: true # Use HTTP instead of HTTPS
    daemon: true # Run the server in the background
    #use_gzip: true # Toggle GZIP compression
    #no_workers: true # Do not start workers

workers:
    docker_compose: ~
