name: minutenbild
services:
    database:
        container_name: minutenbild-postgres
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: minutenbild
            POSTGRES_USER: minutenbild
            POSTGRES_PASSWORD: devpass
            PGDATA: /var/lib/postgresql/data/psql
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "businizer", "-U", "businizer"]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "5432:5432"
        volumes:
            - ${PWD}/../data/postgres:/var/lib/postgresql/data:rw